# Book settings
title: Geographic Data Science for Applied Economists
author: Dani Arribas-Bel & Diego Puga
#logo: logo.jpeg

parse:
  myst_enable_extensions: [
    "amsmath",
    "colon_fence",
    "deflist",
    "dollarmath",
    "html_admonition",
    "html_image",
    "linkify",
    "replacements",
    "smartquotes",
    "substitution"
]

execute:
  execute_notebooks: "off"
repository:
  url: https://github.com/darribas/gds4ae
launch_buttons:
  binderhub_url: https://mybinder.org
  notebook_interface: "jupyterlab"  # or "classic"
  
html:
  google_analytics_id: UA-6032674-1
  extra_footer: |
    <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">Data Science Studio</span> by <a xmlns:cc="http://creativecommons.org/ns#" href="http://darribas.org" property="cc:attributionName" rel="cc:attributionURL">Dani Arribas-Bel</a> and <a xmlns:cc="http://creativecommons.org/ns#" href="https://diegopuga.org/" property="cc:attributionName" rel="cc:attributionURL">Diego Puga</a> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.
    
sphinx:
  config:
    html_show_copyright: false
    
bibtex_bibfiles:
   - content/pages/bibliography.bib