# Environment file to build website on each commit
# For end-users, the gds_env (darribas.org/gds_env) is recommended
name: book
channels:
  - default
  - conda-forge
dependencies:
  - python=3.9.*
  - sphinx=4.5.0
  - pip=22.1
  - nbconvert=6.5.0
  - pip:
      - jupyter-book=0.12.3
      - pyppeteer=1.0.2
